name: Esmail Hello World Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run : echo "Hello Esmail in The world"
        shell: bash
  goodby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodby Esmail
        run : echo "Goodby Esmail"
        shell: bash
