# name: Add a comment on new issues
# on:
#   issues:
#     types: [opened]
# jobs:
#   comment-with-action:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "dump github context"
#         run: echo '${{toJSON(github.event)}}' | jq
#         shell: bash
#       - name: "Create comment"
#         uses: peter-evans/create-or-update-comment@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           repository: ${{ github.repository }}
#           issue-number: ${{ github.event.issue.number }}
#           body: |
#             Hi ${{ github.event.issue.user.login }}!
#           reactions: '+1'


name: Add Comment to New Issue
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="Thank you for opening this issue! We will look into it as soon as possible."
          URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\":\"$COMMENT\"}" "$URL"
